version: "3"
services: 
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    restart: always
    environment: 
      VIRTUAL_HOST: ${VIRTUAL_HOST_backend}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_backend}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  frontend:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    restart: always
    environment: 
      VIRTUAL_HOST: ${VIRTUAL_HOST_frontend}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST_frontend}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
networks:
    default:
       external:
         name: webproxy